### ISSUE TITLE
I don't completely understand the usage

### ISSUE THREAD

**Issue by c8hunderscore** [FrankGrimm/apex7tkl_linux#6]
I understand that you can do commands like `./cli.py config 1` to use different configurations and commands like `./cli.py oledtext "my_text"` but i don't understand how (or if) i can set reactive colors, for example to change a key's color when i tap it.

**Comment by FrankGrimm** [comment]
Hey, apologies, I did not get a notification for your comment. 

I didn't implement changing effects that determine how the keyboard behaves when keys are pressed, color changes are limited to the regular state. I'd guess that is a config level setting, don't really have a setup where I could sniff those instructions at the moment.

- ` ./cli.py color SYMBOLS_LEFT green F1,F2,F3,F4 red -- black` set colors, takes in pairs of (keycode or region, color). The special region "--" sets the following color on all keys that have not been used so far. Definitions in `keys.py`.
- `./cli.py color ALL orange`
- `./cli.py color ALPHA c26838`
- `./cli.py color F9,F10,F11,F12 red`

**Comment by c8hunderscore** [comment]
alright, thanks.
